# Smokable materials and their effects
# Format: MATERIAL: [EFFECT:DURATION:AMPLIFIER, ...]
# Duration is in ticks (20 ticks = 1 second)
# Amplifier is the effect level (0 = level 1, 1 = level 2, etc.)
smokables:
  SHORT_GRASS: []
  FERN: []
  LARGE_FERN: []
  TALL_GRASS: []
  GLOW_LICHEN: [GLOWING:600:0]
  LILY_PAD: [WATER_BREATHING:600:0]
  SEAGRASS: [WATER_BREATHING:400:0]
  TALL_SEAGRASS: [WATER_BREATHING:400:0]
  OAK_LEAVES: [LUCK:400:0]
  SPRUCE_LEAVES: [RESISTANCE:400:0]
  BIRCH_LEAVES: [SPEED:400:0]
  JUNGLE_LEAVES: [JUMP_BOOST:400:0]
  ACACIA_LEAVES: [REGENERATION:200:0]
  DARK_OAK_LEAVES: [DARKNESS:300:0]
  MANGROVE_LEAVES: [POISON:200:0]
  CHERRY_LEAVES: [REGENERATION:300:1]
  AZALEA_LEAVES: [LUCK:300:0]
  FLOWERING_AZALEA_LEAVES: [LUCK:400:1]
  DANDELION: [REGENERATION:200:0]
  POPPY: [SPEED:300:0]
  BLUE_ORCHID: [SATURATION:100:0]
  ALLIUM: [FIRE_RESISTANCE:400:0]
  AZURE_BLUET: [JUMP_BOOST:300:0]
  RED_TULIP: [ABSORPTION:200:0]
  ORANGE_TULIP: [ABSORPTION:200:0]
  WHITE_TULIP: [ABSORPTION:200:0]
  PINK_TULIP: [ABSORPTION:200:0]
  OXEYE_DAISY: [REGENERATION:300:0]
  CORNFLOWER: [NIGHT_VISION:600:0]
  LILY_OF_THE_VALLEY: [POISON:100:0]
  WITHER_ROSE: [WITHER:200:0, NAUSEA:300:0]
  TORCHFLOWER: [GLOWING:400:0]
  SUNFLOWER: [HEALTH_BOOST:400:0]
  LILAC: [LUCK:300:0]
  ROSE_BUSH: [STRENGTH:300:0]
  PEONY: [REGENERATION:400:0]
  PITCHER_PLANT: [SLOW_FALLING:400:0]

# What custom model data should marijuana pipes have?
customModelData: 1

# How much "charge" does each smokable material add? (max 57)
refillAmount: 15
